#!/usr/bin/env python3
"""Static crawlable browse pages for The Signature Book Depository (AI/crawler accessibility).

Generates browse/books-NNN.html (1,000 books per shard, plain <a href> ?book=
deep links, prev/next) + browse/genres.html (16 genres) + browse/index.html.
Re-run any time the catalog changes; sitemap.xml is regenerated by
code/drip_books.py::write_sitemap which now includes these pages.
Purely additive — does not touch index.html's look or behavior.
"""
import gzip, json, os, html, math

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://justinahiggins614-cmyk.github.io/signature-books/"
OUT = os.path.join(ROOT, "browse")
PER = 1000

CSS = """body{font-family:Georgia,'Times New Roman',serif;background:#141009;color:#f0e6cf;margin:0;line-height:1.6}
.wrap{max-width:900px;margin:0 auto;padding:28px 18px}
h1{color:#f2d47e;font-size:1.5em}h2{color:#d9a441;margin-top:1.6em}
a{color:#9fc2ff}.meta{color:#a89e86;font-size:.9em}
.nav{display:flex;justify-content:space-between;margin:18px 0;flex-wrap:wrap;gap:8px}
ul{list-style:none;padding:0}li{margin:.35em 0}
.top{border-bottom:1px solid #4a3d24;padding-bottom:10px;margin-bottom:16px}"""

def page(title, desc, body, canon):
    return ("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
            f"<title>{html.escape(title)}</title>\n"
            f"<meta name=\"description\" content=\"{html.escape(desc)}\">\n"
            f"<link rel=\"canonical\" href=\"{canon}\">\n"
            f"<style>{CSS}</style>\n</head>\n<body>\n<div class=\"wrap\">\n{body}\n</div>\n</body>\n</html>\n")

def main():
    os.makedirs(OUT, exist_ok=True)
    with gzip.open(os.path.join(ROOT, "data", "index", "books.idx.json.gz"), "rt") as f:
        idx = json.load(f)
    n = len(idx)
    shards = math.ceil(n / PER)

    for s in range(shards):
        chunk = idx[s*PER:(s+1)*PER]
        first, last = chunk[0]["id"], chunk[-1]["id"]
        items = "\n".join(
            f'<li><a href="../?book={r["id"]}">{html.escape(r["t"])}</a> '
            f'<span class="meta">{html.escape(r["g"])} &middot; {r["w"]:,} words &middot; {r["id"]}</span></li>'
            for r in chunk)
        prev_ = (f'<a href="books-{s:03d}.html">&larr; Previous 1,000</a>' if s > 0
                 else '<span class="meta">First page</span>')
        next_ = (f'<a href="books-{s+2:03d}.html">Next 1,000 &rarr;</a>' if s < shards-1
                 else '<span class="meta">Last page</span>')
        body = (f'<div class="top"><p class="meta"><a href="../">The Signature Book Depository</a> &middot; '
                f'<a href="index.html">Browse index</a> &middot; <a href="genres.html">Genres</a></p>\n'
                f"<h1>Book catalog \u2014 page {s+1} of {shards}</h1>\n"
                f"<p>{first} through {last}: every book below opens its full finished volume "
                f"(cover, chapters, read-aloud) at its permanent link.</p></div>\n"
                f'<div class="nav">{prev_}{next_}</div>\n<ul>\n{items}\n</ul>\n'
                f'<div class="nav">{prev_}{next_}</div>')
        t = f"Signature books {first}\u2013{last}"
        with open(os.path.join(OUT, f"books-{s+1:03d}.html"), "w") as f:
            f.write(page(t, f"{len(chunk)} finished Signature books, {first} to {last}, each with a permanent book page.", body, BASE+f"browse/books-{s+1:03d}.html"))

    # genres page (one page, one section per genre)
    genres = {}
    for r in idx:
        genres.setdefault(r["g"], []).append(r)
    secs = []
    for g in sorted(genres):
        items = "\n".join(
            f'<li><a href="../?book={r["id"]}">{html.escape(r["t"])}</a> '
            f'<span class="meta">{r["w"]:,} words &middot; {r["id"]}</span></li>'
            for r in genres[g])
        secs.append(f'<h2 id="{html.escape(g.lower().replace(" ", "-").replace(chr(39),""))}">{html.escape(g)} '
                    f'<span class="meta">({len(genres[g]):,} books)</span></h2>\n<ul>\n{items}\n</ul>')
    gbody = (f'<div class="top"><p class="meta"><a href="../">The Signature Book Depository</a> &middot; '
             f'<a href="index.html">Browse index</a></p>\n'
             f"<h1>Browse by genre</h1>\n<p>{len(genres)} genres, {n:,} finished books.</p></div>\n"
             + "\n".join(secs))
    with open(os.path.join(OUT, "genres.html"), "w") as f:
        f.write(page("Signature books \u2014 browse by genre",
                     f"All {n:,} finished Signature books across {len(genres)} genres, each with a permanent book page.",
                     gbody, BASE+"browse/genres.html"))

    shards_links = " ".join(f'<a href="books-{s+1:03d}.html">{s+1}</a>' for s in range(shards))
    ibody = (f'<div class="top"><p class="meta"><a href="../">The Signature Book Depository</a></p>\n'
             f"<h1>Browse the depository</h1>\n"
             f"<p>Static, crawler-friendly index of all {n:,} finished books. Every link is a permanent book URL.</p></div>\n"
             f"<h2>Book pages</h2><p>{shards_links}</p>\n"
             f'<h2>By genre</h2><p><a href="genres.html">16 genres</a></p>')
    with open(os.path.join(OUT, "index.html"), "w") as f:
        f.write(page("The Signature Book Depository \u2014 browse index",
                     f"Static browse index: all {n:,} finished Signature books and 16 genres.",
                     ibody, BASE+"browse/"))
    print(f"wrote {shards} book shards + genres + index ({n} books)")

if __name__ == "__main__":
    main()
